version: '3.8'

services:
  dicom-viewer:
    build:
      context: .
      dockerfile: ./.docker/contexts/${DOCKERFILE:-Dockerfile}
    networks:
      dicom-network:
    environment:
      PORT: ${VIEWER_PORT}

networks:
  dicom-network:
    external: true
